# Generated by Django 5.2 on 2025-06-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frames',
            new_name='Frame',
        ),
        migrations.RenameModel(
            old_name='Lenses',
            new_name='LensProduct',
        ),
    ]
