# Generated by Django 5.2.3 on 2025-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_lensproduct_b_c_alter_frame_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='barcode',
        ),
        migrations.AddField(
            model_name='frame',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='images/barcodes/'),
        ),
        migrations.AddField(
            model_name='frame',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='side',
            field=models.CharField(blank=True, choices=[('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], max_length=20, null=True),
        ),
    ]
