# Generated by Django 5.2.3 on 2025-06-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_frame_barcode_frame_barcode_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='product_code',
        ),
    ]
