# Generated by Django 5.2.3 on 2025-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_frame_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensproduct',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='images/barcodes/'),
        ),
    ]
