# Generated by Django 5.2.3 on 2025-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_lensproduct_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
