# Generated by Django 5.2.3 on 2025-07-02 05:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(default=datetime.date.today)),
                ('distance_sphere', models.FloatField()),
                ('distance_cylinder', models.FloatField()),
                ('distance_axis', models.FloatField()),
                ('distance_va', models.IntegerField()),
                ('near_sphere', models.FloatField()),
                ('near_cylinder', models.FloatField()),
                ('near_axis', models.FloatField()),
                ('near_va', models.IntegerField()),
                ('additional_sphere', models.FloatField()),
                ('contact_sphere', models.FloatField()),
                ('contact_cylinder', models.FloatField()),
                ('contact_axis', models.FloatField()),
                ('contact_va', models.IntegerField()),
                ('pd_right', models.FloatField()),
                ('pd_left', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
        ),
    ]
