# Generated by Django 5.2.3 on 2025-07-02 05:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(blank=True, upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not specify', 'Do not specify')], max_length=20)),
                ('age_group', models.CharField(choices=[('Children (0-14)', 'Children'), ('Youth (15-24)', 'Youth'), ('Adult (25-59)', 'Adult'), ('Senior (60+)', 'Senior')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('second_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
    ]
