# Generated by Django 5.2.3 on 2025-06-24 09:58

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(blank=True, upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not specify', 'Do not specify')], max_length=20)),
                ('age_group', models.CharField(choices=[('Children (0-14)', 'Children'), ('Youth (15-24)', 'Youth'), ('Adult (25-59)', 'Adult'), ('Senior (60+)', 'Senior')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('second_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Dr.', 'Dr.'), ('Optician', 'Optician')], max_length=20)),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(default=datetime.date.today)),
                ('distance_sphere', models.FloatField()),
                ('distance_cylinder', models.FloatField()),
                ('distance_axis', models.FloatField()),
                ('distance_va', models.IntegerField()),
                ('near_sphere', models.FloatField()),
                ('near_cylinder', models.FloatField()),
                ('near_axis', models.FloatField()),
                ('near_va', models.IntegerField()),
                ('additional_sphere', models.FloatField()),
                ('contact_sphere', models.FloatField()),
                ('contact_cylinder', models.FloatField()),
                ('contact_axis', models.FloatField()),
                ('contact_va', models.IntegerField()),
                ('pd_right', models.FloatField()),
                ('pd_left', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('product_purchased', models.CharField(choices=[('Full Specs', 'Full Specs (frame with power)'), ('Only Frame/Sunglasses', 'Only Frame/Sunglasses'), ('Only Lens/Contact Lens', 'Only Lens/Contact Lens')], max_length=100)),
                ('discount', models.FloatField(default=0.0)),
                ('advancePaid', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Upi', 'Upi'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('medicines', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.prescription')),
            ],
        ),
    ]
